package com.github.arhi23.photosocnet.composeui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF476810)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC7F089)

val md_theme_dark_primary = Color(0xFFACD370)
val md_theme_dark_onPrimary = Color(0xFF213600)
val md_theme_dark_primaryContainer = Color(0xFF324F00)

val psnLightPrimary = Color(0xFF815520)
val psnLightOnPrimary = Color(0xFFFFFFFF)
val psnLightPrimaryContainer = Color(0xFFFFDDAE)
val psnLightOnPrimaryContainer = Color(0xFF2A1800)
val psnLightSecondary = Color(0xFF6F5B40)
val psnLightOnSecondary = Color(0xFFFFFFFF)
val psnLightSecondaryContainer = Color(0xFFFADEBC)
val psnLightOnSecondaryContainer = Color(0xFF271904)
val psnLightTertiary = Color(0xFF516440)
val psnLightOnTertiary = Color(0xFFFFFFFF)
val psnLightTertiaryContainer = Color(0xFFD3EABC)
val psnLightOnTertiaryContainer = Color(0xFF102004)
val psnLightError = Color(0xFFBA1B1B)
val psnLightErrorContainer = Color(0xFFFFDAD4)
val psnLightOnError = Color(0xFFFFFFFF)
val psnLightOnErrorContainer = Color(0xFF410001)
val psnLightBackground = Color(0xFFFCFCFC)
val psnLightOnBackground = Color(0xFF1F1B16)
val psnLightSurface = Color(0xFFFCFCFC)
val psnLightOnSurface = Color(0xFF1F1B16)
val psnLightSurfaceVariant = Color(0xFFF0E0CF)
val psnLightOnSurfaceVariant = Color(0xFF4F4539)
val psnLightOutline = Color(0xFF817567)
val psnLightInverseOnSurface = Color(0xFFF9EFE6)
val psnLightInverseSurface = Color(0xFF34302A)
val psnLightPrimaryInverse = Color(0xFFFFB945)

val psnDarkPrimary = Color(0xFFFFB945)
val psnDarkOnPrimary = Color(0xFF452B00)
val psnDarkPrimaryContainer = Color(0xFF624000)
val psnDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val psnDarkSecondary = Color(0xFFDDC3A2)
val psnDarkOnSecondary = Color(0xFF3E2E16)
val psnDarkSecondaryContainer = Color(0xFF56442B)
val psnDarkOnSecondaryContainer = Color(0xFFFADEBC)
val psnDarkTertiary = Color(0xFFB8CEA2)
val psnDarkOnTertiary = Color(0xFF243516)
val psnDarkTertiaryContainer = Color(0xFF3A4C2B)
val psnDarkOnTertiaryContainer = Color(0xFFD3EABC)
val psnDarkError = Color(0xFFFFB4A9)
val psnDarkErrorContainer = Color(0xFF930006)
val psnDarkOnError = Color(0xFF680003)
val psnDarkOnErrorContainer = Color(0xFFFFDAD4)
val psnDarkBackground = Color(0xFF1F1B16)
val psnDarkOnBackground = Color(0xFFEAE1D9)
val psnDarkSurface = Color(0xFF1F1B16)
val psnDarkOnSurface = Color(0xFFEAE1D9)
val psnDarkSurfaceVariant = Color(0xFF4F4539)
val psnDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val psnDarkOutline = Color(0xFF9C8F80)
val psnDarkInverseOnSurface = Color(0xFF32281A)
val psnDarkInverseSurface = Color(0xFFEAE1D9)
val psnDarkPrimaryInverse = Color(0xFF624000)